plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web:4.0.1'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:4.0.1'
    implementation 'org.springframework.boot:spring-boot-starter-security:4.0.1'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client:4.0.1'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf:4.0.1'
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'
    implementation 'org.projectlombok:lombok:1.18.42'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.h2database:h2:2.3.232'
}

test {
    useJUnitPlatform()
}